appname: "go-to-do-app"
server:
  port: 3003
logLevel: "debug"
secretKey: "secret_key_for_todo_app"
secretKeyForExternal: "secret_key_for_todo_app"
aud: api.todoapi.com
iss: todoapi.com
mongoDB:
  url: "mongodb://localhost:27018"
  dbName: "todo_app_db"
  collection: "todolist"
  username: "root"
  password: "root123456"
