appname: "go-to-do-app"
server:
  port: 3001
logLevel: "debug"
secretKey: "secret_key_for_todo_app"
secretKeyForExternal: "secret_key_for_todo_app"
aud: api.todoapi.com
iss: todoapi.com
driverlocation:
  baseUrl: "http://localhost:3000"
