server:
  port: ":3004"
loglevel: debug
couchbase:
  url: "localhost"
  username: "admin"
  password: "123456"
  buckets:
    - name: "todoapp"
      scopes:
        - name: "" # default scope
          collections:
            - name: "todo"