appname: "go-todoapp-app"
server:
  port: 3001
logLevel: "debug"
secretKey: "secret_key_for_todo_app"
secretKeyForExternal: "secret_key_for_todo_app"
aud: api.todoapi.com
iss: todoapi.com
todoapp:
  baseUrl: "http://localhost:3000"
mongoDB:
  url: "mongodb://root:root123456@localhost:27018"
  dbName: "todo_app_db"
  collection: "todolist"
  username: "root"
  password: "123456"

